comparacao_colaborativa_ambienteINSERT INTO comparacao_colaborativa_ambiente (
    id,
    config_tipo,
    config_codigo,
    token,
    convites,
    valido_ate,
    status,
    criado_em,
    atualizado_em,
    matriz_consolidada,
    pesos_consolidados,
    lambda_max,
    indice_consistencia,
    indice_aleatorio,
    razao_consistencia,
    consistente,
    respostas_consolidadas,
    consolidado_em
  )
VALUES (
    'na ',
    'config_tipo:character varying',
    'config_codigo:character varying',
    'token:character varying',
    'convites:jsonb',
    'valido_ate:timestamp with time zone',
    'status:character varying',
    'criado_em:timestamp with time zone',
    'atualizado_em:timestamp with time zone',
    'matriz_consolidada:jsonb',
    'pesos_consolidados:jsonb',
    lambda_max:numeric,
    indice_consistencia:numeric,
    indice_aleatorio:numeric,
    razao_consistencia:numeric,
    consistente:boolean,
    respostas_consolidadas:integer,
    'consolidado_em:timestamp with time zone'
  );