(function(){
  "use strict";
  const API="/api/geoespacial";
  const OPS=[
    ["Entrada e preparação",[["OP-01","Carregar camada","carregar-camada",1],["OP-02","Validar camada","validar-camada",1],["OP-02-CORR","Reparar geometrias","reparar-geometrias",1],["OP-03","Normalizar camada","normalizar-camada",1]]],
    ["Análise vetorial",[["OP-04","Criar buffer","criar-buffer",1],["OP-05","Sobrepor camadas","sobrepor-camadas",1],["OP-06","Dissolver","dissolver",1],["OP-07","Selecionar por localização","selecionar-por-localizacao",1]]],
    ["Transformação",[["OP-08","Converter para raster","converter-para-raster",2]]],
    ["Análise raster",[["OP-10","Calcular distância","calcular-distancia",2],["OP-11","Distância ponderada",null,0],["OP-12","Calcular densidade","calcular-densidade",2],["OP-13","Custo acumulado",null,0],["OP-14","Interpolar valores","interpolar-valores",2],["OP-15","Agregar por território","agregar-por-territorio",1],["OP-16","Criar camada booleana",null,0],["OP-17","Combinar rasters","combinar-rasters",1],["OP-20","Normalizar raster","normalizar-raster",1],["OP-21","Recortar raster",null,0],["OP-22","Estatísticas por zona",null,0]]],
    ["Operações mistas",[["OP-23","Amostrar raster em pontos",null,0],["OP-24","Extrair valores em polígono",null,0]]],
    ["Exportação",[["OP-25","Exportar camada vetorial","exportar-camada",1],["OP-26","Exportar raster","exportar-raster",2],["OP-27","Salvar camada","salvar-camada",1]]]
  ];
  OPS.forEach(([, operations])=>operations.forEach(op=>{op[2]=op[0];op[3]=1}));
  const FIELDS={
    "OP-01":[["tipo_entrada","Tipo de entrada","select",["local","WFS"]],["caminho_arquivo","Caminho ou URL","text"]],
    "OP-02":[["camada_id","Camada","layer"],["validar_intersecoes_invalidas","Validar geometrias","check",true],["validar_crs","Validar CRS","check",true]],
    "OP-02-CORR":[["camada_id","Camada","layer"],["corrigir_geometrias_invalidas","Corrigir geometrias inválidas","check",true],["corrigir_auto_intersecoes","Corrigir auto-interseções","check",true]],
    "OP-03":[["camada_id","Camada","layer"],["crs_destino","CRS de destino","text","EPSG:4674"],["remover_geometrias_vazias","Remover vazias","check",true],["explodir_multipartes","Explodir multipartes","check",false]],
    "OP-04":[["camada_id","Camada","layer"],["distancia_buffer","Distância","number",100],["unidade_buffer","Unidade","select",["metros","graus"]],["tipo_buffer","Tipo","select",["cheio","externo"]],["dissolver_geometrias","Dissolver","check",false]],
    "OP-05":[["camada_id_1","Camada de entrada","layer"],["camada_id_2","Camada de identidade","layer"],["tipo_overlay","Operação","select",["identity","intersection","union","difference"]],["resolver_conflitos_campos","Preservar e resolver atributos","check",true]],
    "OP-06":[["camada_id","Camada","layer"],["campo_agrupamento","Campo de agrupamento","text"],["funcao_agregacao","Agregação","select",["soma","media","mediana","max","min"]]],
    "OP-07":[["camada_id","Camada alvo","layer"],["camada_ref_id","Camada de referência","layer"],["tipo_selecao","Predicado","select",["intersects","contains","within","touches"]],["inverter_selecao","Inverter seleção","check",false]],
    "OP-08":[["camada_id","Camada","layer"],["resolucao_raster","Resolução","number",50],["crs_destino","CRS","text","EPSG:31983"],["atributo_rasterizacao","Atributo","text"],["valor_preenchimento","Valor de fundo","number",0]],
    "OP-10":[["camada_id","Camada","layer"],["resolucao_distancia","Resolução","number",50],["distancia_maxima","Distância máxima","number"],["unidade_distancia","Unidade","select",["metros","graus"]]],
    "OP-12":[["camada_id","Camada de pontos","layer"],["tipo_kernel","Kernel","select",["gaussiano","epanechnikov","quadratic"]],["largura_kernel","Largura de banda","number",1000],["resolucao_kernel","Resolução","number",50]],
    "OP-14":[["camada_id","Camada de pontos","layer"],["metodo_interpolacao","Método","select",["idw","kriging","spline"]],["resolucao_interpolacao","Resolução","number",50],["potencia_interpolacao","Potência IDW","number",2]],
    "OP-15":[["camada_id","Camada","layer"],["campo_unidade","Campo territorial","text"],["funcao_agregacao","Agregação","select",["soma","media","mediana","max","min"]],["atributo_agregacao","Atributo","text"]],
    "OP-17":[["raster_ids","IDs dos rasters (separados por vírgula)","text"],["pesos","Pesos (separados por vírgula)","text"],["operador","Operador","select",["soma","media_ponderada","multiplicacao"]]],
    "OP-20":[["raster_id","ID do raster","text"],["metodo_normalizacao","Método","select",["linear","winsorizacao","quebras_naturais"]],["valor_minimo","Mínimo","number"],["valor_maximo","Máximo","number"]],
    "OP-25":[["camada_id","Camada","layer"],["nome_arquivo","Nome do arquivo","text","saida.gpkg"],["formato_saida","Formato","select",["GeoPackage","GeoJSON","Shapefile"]],["opcao_salvamento","Destino","select",["memoria","persistir_sistema"]]],
    "OP-26":[["raster_id","ID do raster","text"],["nome_arquivo","Nome do arquivo","text","saida.tif"],["formato_saida","Formato","select",["GeoTIFF"]],["comprimir_arquivo","Comprimir","check",true]]
  };
  const BASEMAPS=[{id:"osm",name:"OpenStreetMap",tiles:["https://tile.openstreetmap.org/{z}/{x}/{y}.png"]},{id:"carto-light",name:"Carto Claro",tiles:["https://a.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png"]},{id:"carto-dark",name:"Carto Escuro",tiles:["https://a.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}.png"]},{id:"esri-satellite",name:"Imagem de Satélite",tiles:["https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}"]}];
  Object.assign(FIELDS,{"OP-11":[["camada_id","Camada","layer"],["atributo_peso","Atributo de peso","text"],["resolucao_distancia","Resolução","number",50]],"OP-13":[["raster_id","ID do raster de custo","text"],["origem_linha","Linha de origem","number",0],["origem_coluna","Coluna de origem","number",0]],"OP-16":[["camada_id","Camada","layer"],["resolucao_raster","Resolução","number",50]],"OP-21":[["raster_id","ID do raster","text"],["camada_mascara_id","Camada de máscara","layer"]],"OP-22":[["raster_id","ID do raster","text"],["camada_zona_id","Camada de zonas","layer"]],"OP-23":[["raster_id","ID do raster","text"],["camada_pontos_id","Camada de pontos","layer"]],"OP-24":[["raster_id","ID do raster","text"],["camada_poligono_id","Camada de polígonos","layer"],["estatistica","Estatística","select",["media","soma","min","max"]]]});
  FIELDS["OP-27"]=[["entrada","Camada de entrada","text"],["destino","Destino","text","data/geoespacial"],["saida","Saída","text","camada_saida.gpkg"],["crs","CRS","text","auto"],["formato","Formato","select",["auto","gpkg","geojson","shapefile","geotiff"]]];
  const NO_OUTPUT=new Set(["OP-01","OP-02","OP-22","OP-23","OP-24","OP-25","OP-26","OP-27"]),RASTER_OUTPUT=new Set(["OP-08","OP-10","OP-11","OP-12","OP-13","OP-14","OP-16","OP-17","OP-20","OP-21"]);
  OPS.flatMap(x=>x[1]).forEach(op=>{if(NO_OUTPUT.has(op[0]))return;const raster=RASTER_OUTPUT.has(op[0]),base=op[1].toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"_").replace(/^_|_$/g,"");FIELDS[op[0]].push(["destino","Destino","text","data/geoespacial"],["saida","Saída","text",`${base}_saida.${raster?"tif":"gpkg"}`])});
  const state={map:null,layers:[],basemap:"osm",selected:null,functions:load("gp-functions",[]),flows:load("gp-flows",[]),history:load("gp-history",[])};
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  function load(k,d){try{return JSON.parse(localStorage.getItem(k))||d}catch{return d}}
  function save(k,v){localStorage.setItem(k,JSON.stringify(v));$("#gp-save-state").textContent="Alterações salvas"}
  function icons(){window.lucide?.createIcons({attrs:{"stroke-width":1.7}})}
  function log(msg,type=""){const el=$("#gp-log"),time=new Date().toLocaleTimeString();el.insertAdjacentHTML("beforeend",`<div class="log-${type}">[${time}] ${escapeHtml(msg)}</div>`);el.scrollTop=el.scrollHeight}
  function escapeHtml(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
  function ribbon(tab="mapa"){
    const sets={
      mapa:[["Dados",[["folder-open","Adicionar dados","add",true],["database","Adicionar WFS","wfs"],["map","Basemap","basemap"]]],["Navegação",[["mouse-pointer-2","Explorar","explore"],["maximize","Zoom nas camadas","fit"],["scan","Zoom na seleção","fit-selection"]]],["Seleção",[["mouse-pointer-click","Selecionar","select"],["list-x","Limpar seleção","clear"]]],["Camada",[["table-properties","Tabela de atributos","attributes"],["trash-2","Remover camada","remove"]]]],
      analise:[["Geoprocessamento",[["briefcase","Toolbox","tools",true],["play","Executar","run"],["square","Cancelar","cancel"],["history","Histórico","history"]]],["Configuração",[["sliders-horizontal","Ambientes","environments"],["shield-check","Validar entrada","validate"]]],["Resultados",[["save","Salvar resultado","save-result"],["layers","Adicionar resultado ao mapa","add-result"]]]],
      modelo:[["Funções",[["blocks","Nova função","new-function",true],["pencil","Editar função","edit-function"],["badge-check","Validar função","validate-function"],["play","Executar função","run-function"]]],["Fluxos",[["workflow","Novo fluxo","new-flow",true],["pencil","Editar fluxo","edit-flow"],["badge-check","Validar fluxo","validate-flow"],["play","Executar fluxo","run-flow"]]],["Definições",[["copy","Duplicar","duplicate"],["file-input","Importar definição","import-definition"],["file-output","Exportar definição","export-definition"]]]],
      dados:[["Inspecionar",[["info","Propriedades","properties"],["table-properties","Tabela de atributos","attributes"]]],["Consulta",[["calculator","Calcular campo","calculate-field"],["list-filter","Selecionar por atributo","select-attribute"],["filter","Filtrar camada","filter-layer"]]],["Preparar",[["globe-2","Reprojetar","reproject"],["wrench","Reparar geometria","repair"]]],["Persistir",[["download","Exportar dados","export"],["save","Salvar camada","save-layer"],["refresh-cw","Atualizar fonte","refresh-source"],["trash-2","Remover camada","remove"]]]]
    };
    $("#gp-ribbon-tools").innerHTML=sets[tab].map(([g,items])=>`<div class="ribbon-group" data-label="${g}">${items.map(([i,n,a,t])=>`<button class="ribbon-action ${t?"toolbox":""}" data-action="${a}" title="${n}"><i data-lucide="${i}"></i><span>${n}</span></button>`).join("")}</div>`).join("");icons();
  }
  function initMap(){const sources={},layers=[];BASEMAPS.forEach((b,i)=>{sources[b.id]={type:"raster",tiles:b.tiles,tileSize:256,attribution:"© provedores do mapa"};layers.push({id:`basemap-${b.id}`,type:"raster",source:b.id,layout:{visibility:i?"none":"visible"}})});state.map=new maplibregl.Map({container:"gp-map",center:[-48.5,-22.4],zoom:6.2,style:{version:8,sources,layers}});state.map.addControl(new maplibregl.NavigationControl({showCompass:false}),"bottom-right");state.map.on("mousemove",e=>$("#gp-coordinates").textContent=`${e.lngLat.lng.toFixed(5)}, ${e.lngLat.lat.toFixed(5)}`);state.map.on("zoom",()=>$("#gp-scale").textContent=`Zoom ${state.map.getZoom().toFixed(1)}`)}
  async function refreshLayers(){try{const r=await fetch(`${API}/camadas`);if(r.ok)state.layers=await r.json()}catch(e){log(`Catálogo indisponível: ${e.message}`,"error")}renderLayers()}
  function renderLayers(){const q=$("#gp-layer-search").value.toLowerCase(),items=state.layers.filter(x=>x.nome.toLowerCase().includes(q));const base=BASEMAPS.filter(x=>x.name.toLowerCase().includes(q)).map(x=>`<label class="tree-row"><input type="radio" name="basemap" value="${x.id}" ${state.basemap===x.id?"checked":""}><i data-lucide="map"></i><span class="layer-name">${x.name}</span></label>`).join("");const operational=items.map(x=>`<div class="tree-row" data-layer="${x.id}"><input type="checkbox" checked><i data-lucide="${x.tipo?.toLowerCase().includes("raster")?"grid-3x3":"shapes"}"></i><span class="layer-name">${escapeHtml(x.nome)}</span></div>`).join("");$("#gp-layer-list").innerHTML=`<div class="tree-row"><i data-lucide="chevron-down"></i><i data-lucide="layers-3"></i><strong>Camadas operacionais</strong></div>${operational||'<div class="empty">Nenhuma camada carregada.</div>'}<div class="tree-row"><i data-lucide="chevron-down"></i><i data-lucide="map"></i><strong>Basemap</strong></div>${base}`;icons()}
  function setBasemap(id){state.basemap=id;BASEMAPS.forEach(b=>{const layer=`basemap-${b.id}`;if(state.map.getLayer(layer))state.map.setLayoutProperty(layer,"visibility",b.id===id?"visible":"none")})}
  function renderToolbox(filter=""){const f=filter.toLowerCase();$("#gp-toolbox").innerHTML=OPS.map(([g,ops])=>{const rows=ops.filter(o=>(o[0]+o[1]).toLowerCase().includes(f));return rows.length?`<div class="tool-group"><button class="tool-group-title"><i data-lucide="tool-case"></i>${g}</button>${rows.map(o=>`<button class="tool-row" data-op="${o[0]}"><span class="tool-code">${o[0]}</span><span class="tool-name">${o[1]}</span><span class="availability ${o[3]===2?"partial":""}" title="${o[3]===1?"Disponível":o[3]===2?"Backend em implementação":"Catalogado; motor pendente"}"></span></button>`).join("")}</div>`:""}).join("");icons()}
  function selectOp(id){state.selected=id;$$('[data-right-tab]').forEach(b=>b.classList.toggle("active",b.dataset.rightTab==="tools"));showEditor();const op=OPS.flatMap(x=>x[1]).find(x=>x[0]===id);const fields=FIELDS[id]||[];$("#gp-right-title").textContent=op[1];$("#gp-editor-view").innerHTML=`<div class="editor-head"><button class="icon-btn" data-back title="Voltar"><i data-lucide="arrow-left"></i></button><h2>${op[0]} · ${op[1]}</h2></div><form id="gp-op-form"><div class="editor-body">${fields.length?fields.map(fieldHtml).join(""):`<div class="empty">O algoritmo está catalogado na stack, mas seu contrato de execução ainda não foi implementado no backend.</div>`}</div><div class="editor-actions"><button type="button" class="btn" data-add-function>Adicionar à função</button><button class="btn primary" ${!op[2]?"disabled":""}>Executar</button></div></form>`;icons();$("#gp-op-form").onsubmit=e=>{e.preventDefault();executeOp(op,e.target)};$("[data-back]").onclick=()=>showTools();$("[data-add-function]").onclick=()=>newFunction(id)}
  function fieldHtml(f){const [id,label,type,val]=f;if(type==="check")return `<label class="field-check"><input name="${id}" type="checkbox" ${val?"checked":""}>${label}</label>`;let input;if(type==="select")input=`<select name="${id}">${val.map(x=>`<option>${x}</option>`).join("")}</select>`;else if(type==="layer")input=`<select name="${id}" required><option value="">Selecione…</option>${state.layers.map(x=>`<option value="${x.id}">${escapeHtml(x.nome)}</option>`).join("")}</select>`;else input=`<input name="${id}" type="${type}" value="${val??""}" ${["number","text"].includes(type)?"":""}>`;return `<div class="field"><label>${label}</label>${input}</div>`}
  async function executeOp(op,form){if(!op[2])return;const fd=new FormData(form),params=new URLSearchParams();for(const [k,v] of fd){let value=v;if(["raster_ids","pesos"].includes(k))value=v.split(",").map(x=>x.trim());params.append(k,value)}FIELDS[op[0]]?.filter(f=>f[2]==="check").forEach(f=>params.set(f[0],form.elements[f[0]].checked));log(`Executando ${op[0]} ${op[1]}…`);try{const r=await fetch(`${API}/operacoes/${op[2]}?${params}`,{method:"POST",headers:{Accept:"application/json"}});const body=await r.json();if(!r.ok)throw new Error(body.detail||`HTTP ${r.status}`);log(`${op[0]} concluído.`,"ok");state.history.unshift({at:new Date().toISOString(),op:op[0],name:op[1],status:"concluído",result:body});save("gp-history",state.history.slice(0,100));await refreshLayers()}catch(e){log(`${op[0]} falhou: ${typeof e.message==="string"?e.message:JSON.stringify(e.message)}`,"error");state.history.unshift({at:new Date().toISOString(),op:op[0],name:op[1],status:"erro",result:String(e.message)});save("gp-history",state.history.slice(0,100));$("#gp-log").classList.add("open")}}
  function showTools(){$("#gp-right-title").textContent="Geoprocessamento";$("#gp-tools-view").classList.add("active");$("#gp-editor-view").classList.remove("active")}
  function showEditor(){$("#gp-tools-view").classList.remove("active");$("#gp-editor-view").classList.add("active")}
  function newFunction(seed){showEditor();$("#gp-right-title").textContent="Editor de função";const chosen=seed?[seed]:[];builder("function",chosen)}
  function newFlow(){showEditor();$("#gp-right-title").textContent="Editor de fluxo";builder("flow",[])}
  function builder(type,chosen){const isFn=type==="function",pool=isFn?OPS.flatMap(x=>x[1]).map(o=>[o[0],`${o[0]} · ${o[1]}`]):state.functions.map(f=>[f.id,f.name]);$("#gp-editor-view").innerHTML=`<div class="editor-head"><button class="icon-btn" data-back><i data-lucide="arrow-left"></i></button><h2>${isFn?"Nova função":"Novo fluxo"}</h2></div><form id="gp-builder"><div class="editor-body"><div class="field"><label>Nome</label><input name="name" required></div><div class="field"><label>Descrição</label><textarea name="description"></textarea></div><div class="field"><label>${isFn?"Adicionar operador":"Adicionar função"}</label><select id="gp-pool"><option value="">Selecione…</option>${pool.map(p=>`<option value="${p[0]}">${escapeHtml(p[1])}</option>`).join("")}</select></div><div id="gp-builder-list" class="builder-list"></div></div><div class="editor-actions"><button class="btn primary">Salvar</button></div></form>`;const render=()=>$("#gp-builder-list").innerHTML=chosen.map((id,i)=>`<div class="builder-item"><i class="drag" data-lucide="grip-vertical"></i><strong>${escapeHtml(pool.find(p=>p[0]===id)?.[1]||id)}</strong><button type="button" class="icon-btn" data-remove="${i}"><i data-lucide="x"></i></button></div>`).join("");render();icons();$("#gp-pool").onchange=e=>{if(e.target.value){chosen.push(e.target.value);e.target.value="";render();icons()}};$("#gp-builder-list").onclick=e=>{const b=e.target.closest("[data-remove]");if(b){chosen.splice(+b.dataset.remove,1);render();icons()}};$("[data-back]").onclick=showTools;$("#gp-builder").onsubmit=e=>{e.preventDefault();const obj={id:`${type}-${Date.now()}`,name:e.target.name.value,description:e.target.description.value,items:chosen};const list=isFn?state.functions:state.flows;list.push(obj);save(isFn?"gp-functions":"gp-flows",list);log(`${isFn?"Função":"Fluxo"} “${obj.name}” salvo.`,"ok");showLibrary(isFn?"functions":"flows")}}
  function showLibrary(kind){showEditor();const isFn=kind==="functions",list=isFn?state.functions:state.flows;$("#gp-right-title").textContent=isFn?"Funções":"Fluxos";$("#gp-editor-view").innerHTML=`<div class="editor-head"><h2>${isFn?"Funções":"Fluxos"}</h2><button class="btn primary" data-new>${isFn?"Nova função":"Novo fluxo"}</button></div>${list.length?`<div class="editor-body builder-list">${list.map(x=>`<div class="builder-item"><i data-lucide="${isFn?"blocks":"workflow"}"></i><strong>${escapeHtml(x.name)}</strong><span>${x.items.length}</span><button class="icon-btn danger" data-delete="${x.id}"><i data-lucide="trash-2"></i></button></div>`).join("")}</div>`:`<div class="empty">Nenhum item criado.</div>`}`;icons();$("[data-new]").onclick=()=>isFn?newFunction():newFlow();$("#gp-editor-view").onclick=e=>{const b=e.target.closest("[data-delete]");if(!b)return;const i=list.findIndex(x=>x.id===b.dataset.delete);list.splice(i,1);save(isFn?"gp-functions":"gp-flows",list);showLibrary(kind)}}
  function showHistory(){showEditor();$("#gp-right-title").textContent="Histórico";$("#gp-editor-view").innerHTML=state.history.length?`<div class="editor-body builder-list">${state.history.map(x=>`<div class="builder-item"><i data-lucide="${x.status==="erro"?"circle-x":"circle-check"}"></i><strong>${x.op} · ${escapeHtml(x.name)}</strong><span>${new Date(x.at).toLocaleString()}</span></div>`).join("")}</div>`:`<div class="empty">Nenhuma execução registrada.</div>`;icons()}
  async function filesAdded(files){for(const file of files){if(!/\.(geojson|json)$/i.test(file.name)){log(`${file.name}: use a operação Carregar camada para formatos processados no servidor.`,"error");continue}try{const data=JSON.parse(await file.text()),id=`local-${Date.now()}-${Math.random().toString(16).slice(2)}`;state.map.addSource(id,{type:"geojson",data});state.map.addLayer({id,type:"fill",source:id,paint:{"fill-color":"#1683c4","fill-opacity":.32,"fill-outline-color":"#075b89"},filter:["==",["geometry-type"],"Polygon"]});state.map.addLayer({id:id+"-line",type:"line",source:id,paint:{"line-color":"#075b89","line-width":2}});state.map.addLayer({id:id+"-point",type:"circle",source:id,paint:{"circle-color":"#d97819","circle-radius":5,"circle-stroke-color":"#fff","circle-stroke-width":1}});state.layers.unshift({id,nome:file.name,tipo:"GeoJSON",origem:"local"});renderLayers();const bounds=new maplibregl.LngLatBounds();data.features?.forEach(f=>walkCoords(f.geometry?.coordinates,c=>bounds.extend(c)));if(!bounds.isEmpty())state.map.fitBounds(bounds,{padding:40});log(`${file.name} adicionado ao mapa.`,"ok")}catch(e){log(`${file.name}: ${e.message}`,"error")}}}
  function walkCoords(v,cb){if(!Array.isArray(v))return;if(typeof v[0]==="number")cb(v);else v.forEach(x=>walkCoords(x,cb))}
  function bind(){ribbon();renderToolbox();refreshLayers();$("#gp-tool-search").oninput=e=>renderToolbox(e.target.value);$("#gp-layer-search").oninput=renderLayers;$("#gp-toolbox").onclick=e=>{const b=e.target.closest("[data-op]");if(b)selectOp(b.dataset.op)};$$('[data-ribbon]').forEach(b=>b.onclick=()=>{$$('[data-ribbon]').forEach(x=>x.classList.toggle("active",x===b));ribbon(b.dataset.ribbon)});$("#gp-ribbon-tools").onclick=e=>{const a=e.target.closest("[data-action]")?.dataset.action;if(a==="add")$("#gp-file-input").click();if(a==="tools")showTools();if(a==="fit")state.map.fitBounds([[-53.2,-25.5],[-44.0,-19.5]],{padding:20});if(a==="new-function")newFunction();if(a==="new-flow")newFlow();if(a==="history")showHistory()};$$('[data-right-tab]').forEach(b=>b.onclick=()=>{$$('[data-right-tab]').forEach(x=>x.classList.toggle("active",x===b));if(b.dataset.rightTab==="tools")showTools();else if(b.dataset.rightTab==="history")showHistory();else showLibrary(b.dataset.rightTab)});$("#gp-file-input").onchange=e=>filesAdded(e.target.files);const mapView=$(".gp-map-view");["dragenter","dragover"].forEach(n=>mapView.addEventListener(n,e=>{e.preventDefault();mapView.classList.add("dragging")}));["dragleave","drop"].forEach(n=>mapView.addEventListener(n,e=>{e.preventDefault();mapView.classList.remove("dragging")}));mapView.addEventListener("drop",e=>filesAdded(e.dataTransfer.files));$("#gp-home").onclick=()=>state.map.flyTo({center:[-48.5,-22.4],zoom:6.2});$("#gp-fit").onclick=()=>state.map.fitBounds([[-53.2,-25.5],[-44,-19.5]],{padding:20});$("#gp-log-toggle").onclick=()=>$("#gp-log").classList.toggle("open");$$('[data-collapse]').forEach(b=>b.onclick=()=>$(".gp-app").classList.toggle(`${b.dataset.collapse}-collapsed`))}
  executeOp=async function(op,form){const fd=new FormData(form),params={};for(const [k,v] of fd)params[k]=form.elements[k]?.type==="number"&&v!==""?Number(v):v;for(const k of ["raster_ids","pesos"]){if(typeof params[k]==="string")params[k]=params[k].split(",").map(x=>k==="pesos"?Number(x.trim()):x.trim())}FIELDS[op[0]]?.filter(f=>f[2]==="check").forEach(f=>params[f[0]]=form.elements[f[0]].checked);log(`Executando ${op[0]} ${op[1]}…`);try{const r=await fetch(`${API}/algoritmos/${op[0]}/executar`,{method:"POST",headers:{Accept:"application/json","Content-Type":"application/json"},body:JSON.stringify(params)});const body=await r.json();if(!r.ok)throw new Error(body.detail||`HTTP ${r.status}`);log(`${op[0]} concluído.`,"ok");state.history.unshift({at:new Date().toISOString(),op:op[0],name:op[1],status:"concluído",result:body});save("gp-history",state.history.slice(0,100));await refreshLayers()}catch(e){log(`${op[0]} falhou: ${e.message}`,"error");$("#gp-log").classList.add("open")}};
  function showProperties(layer){showEditor();$("#gp-right-title").textContent="Propriedades";if(!layer){$("#gp-editor-view").innerHTML='<div class="empty">Selecione um recurso no Catálogo ou um objeto no painel Conteúdo para consultar e editar suas propriedades.</div>';return}$("#gp-editor-view").innerHTML=`<div class="editor-head"><i data-lucide="${layer.tipo?.toLowerCase().includes("raster")?"grid-3x3":"shapes"}"></i><h2>${escapeHtml(layer.nome)}</h2></div><div class="editor-body"><dl class="property-list"><dt>Identificador</dt><dd>${escapeHtml(layer.id)}</dd><dt>Tipo</dt><dd>${escapeHtml(layer.tipo||"Camada")}</dd><dt>CRS</dt><dd>${escapeHtml(layer.crs||"Não informado")}</dd><dt>Origem</dt><dd>${escapeHtml(layer.origem||"Sessão")}</dd><dt>Importação</dt><dd>${escapeHtml(layer.data_importacao||"Sessão atual")}</dd></dl></div>`;icons()}
  document.addEventListener("DOMContentLoaded",()=>{initMap();bind();showProperties(null);$("#gp-layer-list").addEventListener("change",e=>{if(e.target.name==="basemap")setBasemap(e.target.value)});$("#gp-layer-list").addEventListener("click",e=>{const row=e.target.closest("[data-layer]");if(!row)return;$$('[data-layer]').forEach(x=>x.classList.toggle("active",x===row));showProperties(state.layers.find(x=>x.id===row.dataset.layer))});$("#gp-catalog-tree").addEventListener("click",e=>{const row=e.target.closest(".tree-row");if(!row)return;$$('.gp-catalog-tree .tree-row').forEach(x=>x.classList.toggle("active",x===row));showProperties({id:row.textContent.trim().toLowerCase().replaceAll(" ","_"),nome:row.textContent.trim(),tipo:"Recurso do projeto",origem:"Catálogo"})});$$('[data-restore]').forEach(b=>b.onclick=()=>$(".gp-app").classList.remove(`${b.dataset.restore}-collapsed`));icons();log("Ambiente de geoprocessamento inicializado.","ok")});
  const TOOL_SUBGROUPS={"OP-01":"Importação e conexão","OP-02":"Qualidade e preparação","OP-02-CORR":"Qualidade e preparação","OP-03":"Qualidade e preparação","OP-04":"Geometria e proximidade","OP-05":"Sobreposição espacial","OP-06":"Agregação vetorial","OP-07":"Consulta e seleção","OP-08":"Conversão de dados","OP-10":"Distância e custo","OP-11":"Distância e custo","OP-12":"Densidade e distribuição","OP-13":"Distância e custo","OP-14":"Interpolação e superfície","OP-15":"Agregação territorial","OP-16":"Criação de superfície","OP-17":"Álgebra de mapas","OP-20":"Normalização raster","OP-21":"Recorte e máscara","OP-22":"Estatística zonal","OP-23":"Amostragem raster","OP-24":"Extração zonal","OP-25":"Dados vetoriais","OP-26":"Dados raster"};
  renderToolbox=function(filter=""){const term=filter.toLocaleLowerCase("pt-BR"),collator=new Intl.Collator("pt-BR",{sensitivity:"base"}),groups=[...OPS].sort((a,b)=>collator.compare(a[0],b[0]));$("#gp-toolbox").innerHTML=groups.map(([group,operations])=>{const filtered=operations.filter(op=>op[1].toLocaleLowerCase("pt-BR").includes(term)).sort((a,b)=>collator.compare(a[1],b[1]));if(!filtered.length)return"";const subgroups=Object.groupBy?Object.groupBy(filtered,op=>TOOL_SUBGROUPS[op[0]]||"Outros"):filtered.reduce((acc,op)=>((acc[TOOL_SUBGROUPS[op[0]]||"Outros"]??=[]).push(op),acc),{});return`<div class="tool-group"><button class="tool-group-title" aria-expanded="true"><i data-lucide="chevron-down"></i><i data-lucide="tool-case"></i><span>${group}</span></button><div class="tool-group-children">${Object.entries(subgroups).sort(([a],[b])=>collator.compare(a,b)).map(([sub,items])=>`<div class="tool-subgroup"><button class="tool-subgroup-title" aria-expanded="true"><i data-lucide="chevron-down"></i><span>${sub}</span></button><div class="tool-subgroup-children">${items.map(op=>`<button class="tool-row" data-op="${op[0]}" title="${op[1]}"><i data-lucide="settings-2"></i><span class="tool-name">${op[1]}</span><span class="availability" title="Disponível"></span></button>`).join("")}</div></div>`).join("")}</div></div>`}).join("");icons()};
  fieldHtml=function(f){const[id,label,type,val]=f,prefix=id==="nome_saida"?'<div class="form-section-title"><i data-lucide="save"></i><span>Saída</span></div>':"";if(type==="check")return`${prefix}<label class="field-check"><input name="${id}" type="checkbox" ${val?"checked":""}>${label}</label>`;let input;if(type==="select")input=`<select name="${id}">${val.map(x=>`<option value="${x}">${x}</option>`).join("")}</select>`;else if(type==="layer")input=`<select name="${id}" required><option value="">Selecione…</option>${state.layers.map(x=>`<option value="${x.id}">${escapeHtml(x.nome)}</option>`).join("")}</select>`;else input=`<input name="${id}" type="${type}" value="${val??""}>`;return`${prefix}<div class="field"><label>${label}</label>${input}</div>`};
  TOOL_SUBGROUPS["OP-27"]="Persistência";
  window.gpApp={state,selectOp,showProperties,showLibrary,showHistory,renderLayers,setBasemap,renderToolbox};
})();
