(function () {
  "use strict";
  const $ = (s) => document.querySelector(s), esc = (v) => String(v ?? "—").replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const queryCode = new URLSearchParams(location.search).get("codigo");
  let hierarquizacoes = [], pares = [], fatiamentos = [];
  const atual = () => hierarquizacoes.find(x => x.codigo === $("#fase-hierarquizacao").value);
  const parAtual = () => pares.find(x => x.pacote_id === $("#camada-restricao").selectedOptions[0]?.dataset.par);
  function linha(label, value) { return `<div><dt>${esc(label)}</dt><dd>${esc(value)}</dd></div>`; }
  function erro(value) { const box=$("#fase1-erro"); box.textContent=value?.message||value; box.classList.remove("hidden"); }
  function objetos(h) { return h?.dados_hierarquizacao?.objetos || (h?.objetos || []).map(o => ({cabecalho_objeto:o})); }
  function renderHierarquizacao() {
    const h=atual(), box=$("#fase-resumo"), layer=$("#gp-demandas");
    if(!h){box.classList.add("hidden");layer.innerHTML='<p class="ahp-help-text">Selecione uma hierarquização.</p>';return;}
    const list=objetos(h).slice(0,10).map((o,i)=>{const c=o.cabecalho_objeto||o;return `<li>${esc(c.codigo||c.demanda_id||`Objeto ${i+1}`)} — ${esc(c.nome||"Sem denominação")}</li>`}).join("");
    box.innerHTML=`<dl>${linha("Código",h.codigo)}${linha("Configuração multicritério",h.config_codigo||h.config_id)}${linha("Nome",h.nome)}<div><dt>Objetos (primeiros 10)</dt><dd><ol>${list||"<li>Nenhum objeto</li>"}</ol></dd></div></dl>`;box.classList.remove("hidden");
    layer.innerHTML=`<span class="fase1-layer"><i class="fas fa-location-dot"></i><span><strong>${esc(h.nome)}</strong><small>${objetos(h).length} ponto(s), espacializados por latitude/longitude</small></span></span>`;
  }
  function finalidade(c,t){return (String(c.finalidade||"")+JSON.stringify(c.metadados||{})).toLowerCase().includes(t)}
  function preencherRestricoes(){const s=$("#camada-restricao");const opts=[];pares.forEach(p=>(p.camadas||[]).filter(c=>finalidade(c,"restri")).forEach(c=>opts.push(`<option value="${esc(c.id)}" data-par="${esc(p.pacote_id)}">${esc(c.nome)} — ${esc(p.nome)} (${esc(p.versao)})</option>`)));s.innerHTML='<option value="">Selecione…</option>'+opts.join("");}
  function associarRiscos(){const p=parAtual(), r=$("#camada-risco");if(!p){r.disabled=true;r.innerHTML='<option value="">Selecione primeiro a camada de restrição</option>';$("#gp-risco-restricao").innerHTML='<p class="ahp-help-text">Selecione o par homologado.</p>';return;}const riscos=(p.camadas||[]).filter(c=>finalidade(c,"risco"));r.innerHTML=riscos.map(c=>`<option value="${esc(c.id)}">${esc(c.nome)} — ${esc(c.versao)}</option>`).join("")||'<option value="">Camada associada não encontrada</option>';r.disabled=!riscos.length;renderCamadas();}
  function renderCamadas(){const p=parAtual(), cr=$("#camada-restricao").selectedOptions[0], ck=$("#camada-risco").selectedOptions[0];if(!p)return;$("#gp-risco-restricao").innerHTML=`<p class="fase1-pair-id">Identificador do conjunto: <code>${esc(p.pacote_id)}</code></p>${cr?.value?`<span class="fase1-layer"><i class="fas fa-ban"></i><span><strong>Restrição: ${esc(cr.textContent)}</strong></span></span>`:""}${ck?.value?`<span class="fase1-layer"><i class="fas fa-triangle-exclamation"></i><span><strong>Risco: ${esc(ck.textContent)}</strong></span></span>`:""}`;}
  const componentesPeso=[['prazo','Prazo regulamentar'],['institucional','Complexidade institucional']];
  function renderFatiamento(){const f=fatiamentos.find(x=>x.id===$("#fatiamento-fase1").value),box=$("#fatiamento-resumo"),weights=$("#fatiamento-pesos");if(!f){box.classList.add("hidden");weights.innerHTML=componentesPeso.map(x=>`<label>${x[1]}<input value="—" readonly></label>`).join('');return;}const p=f.parametros||{}, classes=(p.risco?.classes||[]).map(c=>`${c.rotulo}: ${c.minimo??"−∞"} a ${c.maximo??"+∞"}`).join("; ");box.innerHTML=`<dl>${linha("Nome",f.nome)}${linha("Código",f.codigo)}${linha("Configuração padrão",f.padrao?"Sim":"Não")}${linha("Limiar de restrição",p.restricao?.limiar)}${linha("Classes de risco",classes)}</dl>`;box.classList.remove("hidden");weights.innerHTML=componentesPeso.map(([id,nome])=>`<label>${nome}<input value="${esc(p.pesos?.[id]??'—')}" readonly></label>`).join('');}
  async function executar(){const h=atual(),p=parAtual(),cr=$("#camada-restricao").value,ck=$("#camada-risco").value,f=$("#fatiamento-fase1").value;if(!h||!p||!cr||!ck||!f)return erro("Selecione a hierarquização, as duas camadas e o fatiamento.");try{$("#executar-fase1").disabled=true;const u=await HierApi.executarFase1(h.codigo,{par_id:p.pacote_id,camada_restricao_id:cr,camada_risco_id:ck,configuracao_fatiamento_id:f});hierarquizacoes=hierarquizacoes.map(x=>x.codigo===u.codigo?u:x);const b=$("#fase1-relatorio");b.innerHTML=`<h3>Relatório do processamento</h3><pre>${esc(JSON.stringify(u.relatorio_fase1,null,2))}</pre>`;b.classList.remove("hidden");renderHierarquizacao();}catch(e){erro(e)}finally{$("#executar-fase1").disabled=false}}
  async function init(){try{[hierarquizacoes,pares,fatiamentos]=await Promise.all([HierApi.listar(),HierApi.listarPacotes("fase1"),HierApi.listarFatiamentosFase1()]);const h=$("#fase-hierarquizacao");h.innerHTML='<option value="">Selecione…</option>'+hierarquizacoes.map(x=>`<option value="${esc(x.codigo)}">${esc(x.codigo)} — ${esc(x.nome)}</option>`).join("");if(queryCode)h.value=queryCode;preencherRestricoes();const f=$("#fatiamento-fase1");f.innerHTML=fatiamentos.map(x=>`<option value="${esc(x.id)}" ${x.padrao?"selected":""}>${esc(x.nome)}${x.padrao?" (padrão)":""}</option>`).join("");renderHierarquizacao();renderFatiamento();h.onchange=renderHierarquizacao;$("#camada-restricao").onchange=associarRiscos;$("#camada-risco").onchange=renderCamadas;f.onchange=renderFatiamento;$("#executar-fase1").onclick=executar;}catch(e){erro(e)}}
  init();
})();
